<!-- For test only -->
Show hide window
<a href="javascript:void($zopim.livechat.window.hide())">Hide</a>
<a href="javascript:void($zopim.livechat.window.show())">Show</a>
<a href="javascript:void($zopim.livechat.window.setOffsetVertical(20));">Position vertical 20</a>
<a href="javascript:void($zopim.livechat.window.setOffsetHorizontal(30));">Position horizontal 40</a>
Window Position
<a href="javascript:void($zopim.livechat.window.setPosition('br'))">Bottom right</a>
<a href="javascript:void($zopim.livechat.window.setPosition('bl'))">Bottom left</a>
<a href="javascript:void($zopim.livechat.window.setPosition('tr'))">Top right</a>
<a href="javascript:void($zopim.livechat.window.setPosition('tl'))">Top left</a>
<br/>
Show hide Button
<a href="javascript:void($zopim.livechat.button.hide())">Hide</a>
<a href="javascript:void($zopim.livechat.button.show())">Show</a>
<br/>
Show Hide Bubble
<a href="javascript:void($zopim.livechat.bubble.hide())">Hide</a>
<a href="javascript:void($zopim.livechat.bubble.show())">Show</a>
<br>
Position
<a href="javascript:void($zopim.livechat.button.setPosition('tr'))">Top right</a>
<a href="javascript:void($zopim.livechat.button.setPosition('tm'))">Top middle</a>
<a href="javascript:void($zopim.livechat.button.setPosition('br'))">Bottom right</a>
<a href="javascript:void($zopim.livechat.button.setPosition('bm'))">Bottom middle</a>
<br>
