<?php
/**
 * Diglin
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category    Diglin
 * @package     Diglin_Chat
 * @copyright   Copyright (c) 2011-2015 Diglin (http://www.diglin.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<!-- For test only -->
Show hide window
<a href="javascript:void($zopim.livechat.window.hide())">Hide</a>
<a href="javascript:void($zopim.livechat.window.show())">Show</a>
<a href="javascript:void($zopim.livechat.window.setOffsetVertical(20));">Position vertical 20 (Only new widget)</a>
<a href="javascript:void($zopim.livechat.window.setOffsetHorizontal(30));">Position horizontal 40 (Only new widget)</a>
<br>
Change size (Only new widget)
<a href="javascript:void($zopim.livechat.window.setSize('small'))">small</a>
<a href="javascript:void($zopim.livechat.window.setSize('medium'))">medium</a>
<a href="javascript:void($zopim.livechat.window.setSize('large'))">large</a>
<br>
Window Position
<a href="javascript:void($zopim.livechat.window.setPosition('br'))">Bottom right</a>
<a href="javascript:void($zopim.livechat.window.setPosition('bl'))">Bottom left</a>
<a href="javascript:void($zopim.livechat.window.setPosition('tr'))">Top right</a>
<a href="javascript:void($zopim.livechat.window.setPosition('tl'))">Top left</a>
<br/>
Show hide Button
<a href="javascript:void($zopim.livechat.button.hide())">Hide</a>
<a href="javascript:void($zopim.livechat.button.show())">Show</a>
<a href="javascript:void($zopim.livechat.button.setOffsetBottom(20))">Position Offset Bottom 20 (Only new widget)</a>
<a href="javascript:void($zopim.livechat.button.setOffsetVertical(40))">Position Offset Vertical 40 (Only new widget)</a>
<br/>
Show Hide Bubble
<a href="javascript:void($zopim.livechat.bubble.hide())">Hide</a>
<a href="javascript:void($zopim.livechat.bubble.show())">Show</a>
<br>
Position
<a href="javascript:void($zopim.livechat.button.setPosition('tr'))">Top right</a>
<a href="javascript:void($zopim.livechat.button.setPosition('tm'))">Top middle</a>
<a href="javascript:void($zopim.livechat.button.setPosition('br'))">Bottom right</a>
<a href="javascript:void($zopim.livechat.button.setPosition('bm'))">Bottom middle</a>
<br>
Select Widget Type
<a href="javascript:void($zopim.livechat.theme.setTheme('simple'))">Simple</a>
<a href="javascript:void($zopim.livechat.theme.setTheme('classic'))">Classic</a>
<br>
Select Window Theme Type (Old Widget)
<a href="javascript:void($zopim.livechat.window.setTheme('alphacube'))">Alphacube</a>
<a href="javascript:void($zopim.livechat.window.setTheme('plastic'))">Plastic</a>
<a href="javascript:void($zopim.livechat.window.setTheme('solid'))">solid</a>
<a href="javascript:void($zopim.livechat.window.setTheme('macos'))">Macos</a>
<a href="javascript:void($zopim.livechat.window.setTheme('window7'))">Windows7</a>
<a href="javascript:void($zopim.livechat.window.setTheme('chrome'))">Chrome</a>
<a href="javascript:void($zopim.livechat.window.setTheme('floral'))">Floral</a>
