<?php
/**
 * Diglin GmbH - Switzerland
 *
 * @author      Sylvain Rayé <sylvain.raye at diglin.com>
 * @category    magento
 * @package     magento
 * @copyright   Copyright (c) 2011-2015 Diglin (http://www.diglin.com)
 */

/* @var $this Mage_Core_Block_Template */

$user = Mage::getSingleton('admin/session')->getUser();
$isEnabled = Mage::getStoreConfigFlag('chat/chatconfig/stats');
$appid = Mage::getStoreConfig('chat/chatconfig/appid');

if ($isEnabled && $user && $user->getUsername()): ?>
<script>
    window.intercomSettings = {
        name: "<?php echo $user->getFirstname() . ' ' . $user->getLastname(); ?>",
        email: "<?php echo $user->getEmail(); ?>",
        created_at: <?php echo strtotime($user->getCreated()); ?>,
        app_id: "<?php echo $appid ?>"
    };
</script>
<script>(function(){var w=window;var ic=w.Intercom;if(typeof ic==="function"){ic('reattach_activator');ic('update',intercomSettings);}else{var d=document;var i=function(){i.c(arguments)};i.q=[];i.c=function(args){i.q.push(args)};w.Intercom=i;function l(){var s=d.createElement('script');s.type='text/javascript';s.async=true;s.src='https://widget.intercom.io/widget/<?php echo $appid ?>';var x=d.getElementsByTagName('script')[0];x.parentNode.insertBefore(s,x);}if(w.attachEvent){w.attachEvent('onload',l);}else{w.addEventListener('load',l,false);}}})()</script>
<?php endif; ?>