<!-- For test only -->
Show hide window
<a href="javascript:void($zopim.livechat.window.hide())">Hide</a>
<a href="javascript:void($zopim.livechat.window.show())">Show</a>
<br/>
Show hide Button
<a href="javascript:void($zopim.livechat.button.hide())">Hide</a>
<a href="javascript:void($zopim.livechat.button.show())">Show</a>
<br/>
Show Hide Bubble
<a href="javascript:void($zopim.livechat.bubble.hide())">Hide</a>
<a href="javascript:void($zopim.livechat.bubble.show())">Show</a>

Position
<a href="javascript:void($zopim.livechat.button.setPosition('mr'))">milieu droit</a>
<a href="javascript:void($zopim.livechat.button.setPosition('br'))">Bottom right</a>

